# Generated by Django 5.0.4 on 2024-04-18 10:03

import django.core.validators
import django.db.models.deletion
import extra_services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=extra_services.Uploading_Files.file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt']), django.core.validators.MaxValueValidator(5242880)], verbose_name='File')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
