# Generated by Django 5.0.4 on 2024-04-18 09:55

import django.utils.timezone
import extra_services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(blank=True, choices=[('no-gender', 'Rather not to say'), ('male', 'Male'), ('female', 'Female')], default='no-gender', max_length=50, null=True, verbose_name='Gender')),
                ('image', models.ImageField(default='images/no-photo.jpg', upload_to=extra_services.Uploading_Files.file_name, verbose_name='Image')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('activation_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Activation Code')),
                ('is_active', models.BooleanField(default=False, verbose_name='Being Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Being Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Being Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
