# Generated by Django 5.0.4 on 2024-04-18 10:07

import extra_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/no-photo.jpg', upload_to=extra_services.Uploading_Files.file_name, verbose_name='Image'),
        ),
    ]
