# Generated by Django 5.0.4 on 2024-04-18 10:32

import extra_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/no-photo.jpg', upload_to=extra_services.Uploading_Files.file_name, verbose_name='Image'),
        ),
    ]
